<?php

namespace spec;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

/**
 *
 * Distinct powers
 * 
 * Problem 29
 * 
 * Consider all integer combinations of a^b for 2 ² a ² 5 and 2 ² b ² 5:
 * 
 *     2^2=4, 2^3=8, 2^4=16, 2^5=32
 *     3^2=9, 3^3=27, 3^4=81, 3^5=243
 *     4^2=16, 4^3=64, 4^4=256, 4^5=1024
 *     5^2=25, 5^3=125, 5^4=625, 5^5=3125
 * 
 * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
 * 
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * 
 * How many distinct terms are in the sequence generated by ab for 2 ² a ² 100 and 2 ² b ² 100?
 *
 */
class DistinctPowersSpec extends ObjectBehavior
{
    function it_returns_number_of_terms_for_a_and_b_between_2_and_5()
    {
        $this->countDistinctTerms(2,5)->shouldReturn(15);
    }

    function it_returns_number_of_terms_for_a_and_b_between_2_and_100()
    {
        $this->countDistinctTerms(2,100)->shouldReturn(9183);
    }
}
