<?php

namespace spec;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

/*
 * Problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */
class EvenFibonacciSpec extends ObjectBehavior
{
    function it_returns_2_for_fabinacci_numbers_not_above_3() {
        $this->sum(3)->shouldEqual(2);
    }
    
    function it_returns_10_for_fabinacci_numbers_not_above_10() {
        $this->sum(10)->shouldEqual(10);
    }
    
    function it_returns_44_for_fabinacci_numbers_not_above_35() {
        $this->sum(35)->shouldEqual(44);
    }
    
    function it_returns_44_for_fabinacci_numbers_not_above_100() {
        $this->sum(100)->shouldEqual(2+8+34);
    }
    
    function it_returns_4613732_for_fabinacci_numbers_not_above_4000000() {
        $this->sum(4000000)->shouldEqual(4613732);
    }
    
}
