<?php

/**
 *
 * Distinct powers
 * 
 * Problem 29
 * 
 * Consider all integer combinations of a^b for 2 ² a ² 5 and 2 ² b ² 5:
 * 
 *     2^2=4, 2^3=8, 2^4=16, 2^5=32
 *     3^2=9, 3^3=27, 3^4=81, 3^5=243
 *     4^2=16, 4^3=64, 4^4=256, 4^5=1024
 *     5^2=25, 5^3=125, 5^4=625, 5^5=3125
 * 
 * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
 * 
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * 
 * How many distinct terms are in the sequence generated by ab for 2 ² a ² 100 and 2 ² b ² 100?
 *
 */
class DistinctPowers
{

    /**
     * Count Distinct terms in the sequence generated by ab for min ² a ² max and min ² b ² max
     *
     * @param int $min Minimum value of a and b
     * @param int $max Maximum value of a and b
     *
     * @return int Count
     */
    public function countDistinctTerms($min, $max)
    {
        $count = 0;
        $terms = [];
        
        for ($i = $min; $i <= $max; $i++) {
            for ($j = $min; $j <= $max; $j++) {
                //Use bcpow for accuracy
                $term = bcpow($i, $j);
                
                if (!isset($terms[$term])) {
                    $terms[$term] = 1;
                    $count++;
                }
            }
        }
        
        return $count;
    }
}
