<?php

/**
 *
 * Even Fibonacci numbers
 *
 * Problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */
class EvenFibonacci
{

    /**
     * Find Even Fabonacci Sum for values below $max
     * 
     * @param int $max all Fabonacci values should be below or equal to this value
     * @return int Sum
     */
    public function sum($max)
    {
        $first_term = 1;
        $second_term = 2;
        $sum = 0;
        
        while ($second_term <= $max) {
            if ($second_term % 2 == 0) {
                $sum += $second_term;
            }
            
            $tmp = $first_term + $second_term;
            $first_term = $second_term;
            $second_term = $tmp;
        }
        
        return $sum;
    }
}
